# This is a basic workflow to help you get started with Actions

name: CI

on: [push,  pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    
    - name: Install all of the node modules
      run: npm install

    - name: Run script
      run: node index.js
